#### Install
1. Using Pip -- > pip install opencv-python
2. Using anaconda -- > anaconda install -c anaconda opencv-python

In [1]:
import cv2

In [2]:
# Load the image file from the local folder / dir

image = cv2.imread("Cats4.jpg")
print(f"Image Data type: {type(image)}")
print(f"Image Shape: {image.shape}")
#print(f"Image Read Value: {image}")
print(f"Image Read Value: \n{image[3]}")

Image Data type: <class 'numpy.ndarray'>
Image Shape: (698, 606, 3)
Image Read Value: 
[[241 240 236]
 [241 240 236]
 [241 240 236]
 ...
 [199 211 217]
 [199 210 218]
 [199 210 218]]


In [3]:
image_hight, image_width, color_channel = image.shape
print(f"Image Hight is : {image_hight}")
print(f"Image width is : {image_width}")
print(f"Image color channel is : {color_channel}")

Image Hight is : 698
Image width is : 606
Image color channel is : 3


In [4]:
import cv2
image = cv2.imread("ss.jpg")
image_hight, image_width, color_channel = image.shape
for y in range(image_hight):
    for x in range(image_width):
        input_pixel = image[y, x]
        image[y, x] = [255 - input_pixel[0], 255 - input_pixel[1], 255 - input_pixel[2]]

cv2.imwrite("ManipulatedImageCat.jpg", image)
cv2.imshow("Manipulated Image", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
image = cv2.imread("ss.jpg")
grayImage = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.imshow("Manipulated Image", grayImage)
cv2.waitKey(0)
cv2.destroyAllWindows()